# Generated by Django 4.2.23 on 2025-06-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(to='user.playlist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.album'),
        ),
    ]
