# Generated by Django 4.2.23 on 2025-06-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customuser_playlist_playlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
